### ISSUE TITLE
L02E14 - Wrong robot name

### ISSUE THREAD

**Issue by alvarovillena** [mikeudacity/robo-pace-betatest#102]
This challenge asks to create and print the contents of a directory named 'Tekron3000' instead of 'Tektron3000'. If you create the directory with the real name of the robot, the question is flagged as incorrect.

**Comment by cangelogamboa** [comment]
fixed

**Comment by alvarovillena** [comment]
The challenge description shows now the correct name, but if you create a directory with that name the question is still incorrect. The only way to pass the test is creating the directory as 'Tekron3000'. This should be fixed too.

**Comment by alvarovillena** [comment]
It works now! But there is a typo again in the text: 'give user read, write, execute privileges to the **Tekron3000** directory' should be 'give user read, write, execute privileges to the **Tektron3000** directory'
