### ISSUE TITLE
cornzyblack summary

### ISSUE THREAD

**Issue by cornzyblack** [mikeudacity/robo-pace-betatest#113]
As you review, what do you think other's reaction will be to the experience?

- I think they would consider it to be a nice and new experience, considering the fact that the lessons had cartoons that presented some of the prerequisites by using a relatable story, and it also had challenges that tested their understanding of the material being presented.

For other potential enrollees - are the challenges implemented in a way that makes the context and goals easy to understand and thus rather straightforward to complete ?(assume they have a _some_ background knowledge,)

- Well, assuming they have some background knowledge, Yes!

Is it clear that we're having a bit of fun with the storyline ?

- Yes!

And that very hands-on practical experiences are still to come when the classroom opens.

- Yes, but the hands-on practical experience this content shows is the fact that the Student is going to be programming and calculating.

Do you think it's ok for others to struggle a bit with the quizzes if it's a very real snapshot of the ND's level of intensity?

- Yes, it's ok if others struggle with the quiz as long as hints are also provided.

**Comment by cangelogamboa** [comment]
Thanks for your feedback! I really appreciate you taking the time to let e know your thoughts.
