### ISSUE TITLE
aarvy91

### ISSUE THREAD

**Issue by ravisoni31** [mikeudacity/robo-pace-betatest#117]
It should be 'def moveForward' and not 'def moveFoward'. (However, this is not necessary to run the code.)

**Comment by ravisoni31** [comment]
For L02E16

**Comment by cangelogamboa** [comment]
I am looking into this, thank you for bringing it to my attention.

**Comment by ravisoni31** [comment]
@cangelogamboa  

In the code, it says '#endLocation should be (15,7,E)'. 
But, in the introduction, it says 'walk forward 5 feet'. I think it should be '5 feet' as per the image.

**Comment by cangelogamboa** [comment]
Thanks! I think I have fixed the discrepancies now.
